intercom/intercom-android

README.md

Lint reports the below in Android Studio 2.1...wrong argument being passed.
Wrong 1st argument type. Found: 'android.content.Context', required: 'android.app.Application'
Your to-do list/guide inside your platform indicates this too(the one with prefilled in api credentials)

Update installation instructions for onCreate

---

README.md

Bringing Readme.md in line with https://docs.intercom.io/install-on-your-product-or-site/quick-install/install-intercom-on-your-android-app

Adjust registerIdentifiedUser Readme to match docs

---

README.md

- Fixed numbering by indenting code and note inside each numbered bullet point.
- Fixed two typos.
- Added periods at the end of all comments for consistency.
- Added spaces before opening curly bracket, added a space before opening parenthesis and re-indented some block of code.

Fixed typos and formatting issues in README.md

---

README.md

We are moving our support to our Intercom Developer Hub.

Migrating Customer Support

---

CHANGELOG.md

Custom Bots can now be targeted specifically to your mobile app users! Whether your users are on the web or mobile, Custom Bots now work cross-platform to automate and accelerate growth.
Use our bots to provide better personalization at scale during critical moments of the customer lifecycle like when users first sign up for your app, or when they want to upgrade to a paid plan.
For more details on how to use Custom Bots on mobile, see our [docs here](https://www.intercom.com/help/faqs-and-troubleshooting/custom-bots/do-custom-bots-work-on-mobile).

Update for custom bots

---

README.md

Bringing this in line with our docs - https://developers.intercom.com/installing-intercom/docs/android-fcm-push-notifications#section-step-2-setup-client-to-receive-push
Suggested an edit here too - https://developers.intercom.com/installing-intercom/docs/android-installation#section-option-1-install-intercom-with-firebase-cloud-messaging-fcm-

Update FCM dependencies in readme file

---

CHANGELOG.md

There is an extra `"` in the changelog image URL preventing image from loading https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md
* * * 
This fixes it and you can see it working at https://github.com/thewheat/intercom-android/blob/fix-changelog-screenshot/CHANGELOG.md

Fix screenshot

---

CHANGELOG.md
README.md

* We have redesigned the Help Center for mobile apps. ✨
* New UI, optimized specifically for mobile apps and small screens
* Type-ahead search to help users find answers quicker than ever
* Control whether users open up a specific collection of articles, a group of collections, or specific search results
* Localization - with right to left language display
* Accessibility support: screen readers, dynamic font sizes, and keyboard navigation - to support all end users
* New Help Center Data API that enables you to build your own help center UI, enabling a much deeper and custom integration into your app.
* Fixed an issue where the special notice message would not display.
* `hideMessenger()` has now been deprecated and removed. Please use `hideIntercom()` instead. This method will hide all …

Release 10.0.0

---

CHANGELOG.md

Reduce customer inquiries for your team and provide faster resolutions for your customers – without sacrificing a great experience. We’ve redesigned our Messenger with an integrated help center experience that increases customer engagement by up to 3x to help you deliver the best self-serve support.
New features in this update:
* A new article search card on your Messenger’s home screen.
* There are now two conversation cards, just as with our web Messenger; one for existing and one for new conversations. This gives more emphasis to existing conversations, reducing the chance of duplicates being created.
* Optionally require specific customers to attempt to self-serve to answer their question before they can reach out to a teammate.
* Place the article search card at the top of the …

Release 10.2.0

---

samples/build.gradle
samples/fcm-sample/build.gradle
samples/fcm-sample/src/main/AndroidManifest.xml
samples/gradle/wrapper/gradle-wrapper.properties

Sample app now targets API level 31

Updated sample app to target Android 12

---

sample/.idea/misc.xml
sample/app/src/main/java/com/intercom/sample/MainActivity.kt
sample/app/src/main/java/com/intercom/sample/SampleApplication.kt
sample/app/src/main/res/layout/activity_main.xml
sample/app/src/main/res/values/strings.xml
sample/app/src/main/res/values/themes.xml

Added email to registration
Added validation checks

Update UI 

---

sample/.idea/misc.xml
sample/app/build.gradle
sample/app/src/main/java/com/intercom/sample/MainActivity.kt
sample/app/src/main/java/com/intercom/sample/MainViewModel.kt
sample/app/src/main/res/layout/activity_main.xml
sample/app/src/main/res/values/strings.xml

Updated viewModel
Removed button views

Add viewmodel, removing button dependencies

---

sample/app/src/main/java/com/intercom/sample/components/InputPanel.kt
sample/app/src/main/java/com/intercom/sample/components/SelfServePanel.kt
sample/app/src/main/java/com/intercom/sample/components/TextInputAlertDialog.kt
sample/app/src/main/java/com/intercom/sample/screens/HomeScreen.kt

Unregister user
Close on-screen keyboard (experimental)

Register user by user_id

---

CHANGELOG.md
README.md
sample/app/build.gradle

* We've added Suggested Articles to your Homescreen! Provide a better self-serve experience to your users by enabling them to answer their question before they reach out to a teammate.

Release 10.6.3

---

CHANGELOG.md
README.md
sample/app/build.gradle

* We've added Suggested Articles to your Homescreen! Provide a better self-serve experience to your users by enabling them to answer their question before they reach out to a teammate.

Release 10.7.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed an issue where push notification was not opening the app when tapped on latest Android OS versions

Release 12.1.1

---

sample/app/build.gradle
sample/app/src/main/java/com/intercom/sample/MainActivity.kt
sample/app/src/main/java/com/intercom/sample/screens/HomeScreen.kt

Manages logged-in status and launcher visibility.

Add datastore preferences

---

CHANGELOG.md
README.md
sample/app/build.gradle

New feature: 
You can now open a Survey programmatically in your app. We have added a new method to our API to enable this, [displaySurvey](https://developers.intercom.com/installing-intercom/docs/android-configuration#present-a-survey-programmatically).

Release 12.2.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

Release 12.2.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

Release 12.2.2

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed issue in help center where it did not obey the setting to have at most one open conversation.
* Fixed issues with status bar height on Android 12.
* Fixed issue with truncating expected time on the home screen.
* Improved performance of push notifications
* Intercom now uses Coil 2.0

Release 12.2.3

---

CHANGELOG.md
README.md
sample/app/build.gradle

📱 New Feature : Rich Push Messages 🖼️  
A picture speaks a thousand words. You can now add rich media (i.e. images) to your mobile push messages. Grab your user’s attention by adding attractive and contextual images and increase click-through rate of your push message.
👉  Upgrade to the latest version of the mobile SDK today to use this feature. Additionally, to set rich push messages on iOS, follow the instructions [here](https://developers.intercom.com/installing-intercom/docs/rich-push-notifications).

Release 12.3.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* You can now customize submit button text for surveys sent on your mobile app

Release 12.4.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed a bug that showed the wrong labels under Numeric scale questions in Surveys
* Fixed crash caused due to bad JSON
* Fixed bug that prevented push notification body from expanding

Release 12.4.2

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Made some UI improvements.
* Added the ability to automatically show a Survey when it is set live.

Release 14.0.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

Release 14.1.0

---

CHANGELOG.md
README.md
sample/.idea/misc.xml
sample/app/build.gradle
sample/app/src/main/java/com/intercom/sample/MainApplication.kt

**Meet Fin 👋 a breakthrough AI bot powered by GPT-4, OpenAI's most advanced AI model. Fin solves complex problems and provides safer, more accurate answers than any AI bot on the market.**
| | | |
|-|-|-|
|![Home](https://user-images.githubusercontent.com/10852539/237055121-cef234ba-7130-45ec-96cc-7f4b3a5f420b.png)|![Fin-Intro](https://user-images.githubusercontent.com/10852539/237054858-81dd271a-419b-4192-afa2-2b24ccdcec93.png)|![Fin-Answer](https://user-images.githubusercontent.com/94445025/236837489-31cd957d-dd99-49bf-83e0-d7afe4ab8c91.png)|
**Fin...**
* Holds complete support conversations in plain English, powered by GPT-4 and Intercom’s proprietary ML technology.
* Requires zero setup. Just point it at your help center and turn it on.
* Provides trustworthy, accurate answers based …

Release 15.0.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Improvements to the core conversation screen user experience, better RTL support, bug fixes and performance improvements.

Release 15.1.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed an issue that causes image upload to fail when Identity Verification is turned on

Release 15.1.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

- Bug fixes
- Fix crash when composer is opened with a initial message containing `\n`
- Fix bug where home screen did not update when a new conversation is opened or a reply is received
- Clean up unused dependencies
- Bump dependency versions

Release 15.1.6

---

CHANGELOG.md
README.md
sample/app/build.gradle
sample/app/src/main/java/com/intercom/sample/MainVm.kt
sample/app/src/main/java/com/intercom/sample/components/SelfServePanel.kt

👋 Introducing the new Tickets Space. Enabling the Ticket Space in your Messenger lets end users view and get updates on all their tickets in one location inside the Messenger.
- Fixes crash due to notification bubbles on older Android versions.
- Fixes NullPointerException that might have occured when sending a message.
- Fixes `Manifest merger failed` error when using a FileProvider.
- Enable editing on Attribute Collectors if the value already exists.

Release 15.2.0

---

CHANGELOG.md
README.md
sample/.idea/gradle.xml
sample/.idea/misc.xml
sample/app/build.gradle

**📱 New feature: Set better expectations with your customers by customising the Start Conversation button in your Messenger**
👋 With this release, you can select from a list of options to customize the Start Conversation button in the Messenger. This can be changed in Messenger settings under the "Conversations" section and will affect the Start Conversation button on Messenger Home and in spaces Iike Messages and Help
- Links to create tickets can now be added as a home screen card
- Disables inserting webp images in conversations

Release 15.3.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

- Added camera input type
- Added a button to open previous messages in programmatically launched conversations
- Fixed a crash where Instant class was not found on pre API level 26 devices
👉 This update also removes Lottie as a dependency to the Intercom SDK

Release 15.6.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

- End users can now take videos from the camera in the Messenger
- Added the ability to save images from the conversation
- Fixed the crash while taking a photo from the camera

Release 15.6.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

- Bumped Jetpack Compose version to 1.6
- Added missing translations
- Fixed janky performance on programmatically launched conversation screen

Release 15.6.2

---

CHANGELOG.md
README.md
sample/app/build.gradle

- RTL improvements on the loading screen
- Fixed an issue with push notifications with attachment not working correctly on Android 14
- Fixed issue with message composer when dealing with large messages
- Kotlin Coroutines: Updated from version 1.6.4 to 1.8.0
- Compose Accompanist: Updated from 0.30.1 to 0.34.0
- Compose: Bumped the Compose BOM from 2024.02.00 to 2024.02.01
- Coil: Updated the image loading library from version 2.3.0 to 2.6.0

Release 15.6.4

---

CHANGELOG.md
README.md
sample/app/build.gradle

- Messenger now supports voice to text input
👉 This update also reduces the size Intercom SDK adds to apps by around 1.3 MB

Release 15.7.0

---

LICENSE
sample/build.gradle
sample/gradle/wrapper/gradle-wrapper.properties

1. Updates gradle version of the sample app
2. Updates licenses for all the third party libraries used

Bump gradle plugin version on the sample app

---

CHANGELOG.md
README.md
sample/app/build.gradle

Release 15.8.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

Release 15.8.3

---

CHANGELOG.md
README.md
sample/app/build.gradle

🐛 Bug Fixes
* Fixed attaching photos from camera.
👉 Note
* This release contains some beta features.

Release 15.9.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

- Fixed the issue where push open stats weren’t tracked correctly.
- Fixed the issue where deep links in push message doesn’t work for React Native.
- Attribute collectors are now disabled now if the conversation is closed.
* Kotlin Coroutines: Updated from version 1.8.0 to 1.8.1
* AndroidX Paging: Updated from version 3.2.1 to 3.3.0
* Lifecycle: Updated from version 2.6.2 to 2.8.1
* Gson: Updated from 2.10.1 to 2.11.0

Release 15.9.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

* A newly designed composer for the messenger. 
* Fixes an issue with text fields in surveys.
* Fixed issue allowing customers to start a conversation after reacting to an article.
* Fixes an issue to handle empty message parts for bot introductions.
**Note**
This release contains some beta features.

Release 15.10.0

---

README.md

The images in this repository are out-of-date and reflect an old version of Messenger.

Remove Outdated Images

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed attaching photos and videos from gallery
* Fixed `IndexOutOfBoundsException` crash
* Fixed `IllegalArgumentException` crash caused by non-negative bottom padding
* Coil: Updated from 2.6.0 to 2.7.0
* MP4 Parser: Migrated from `com.googlecode.mp4parser:isoparser` to `org.mp4parser:isoparser`

Release 15.10.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Bug fixes and performance improvements
* Bumped the Compose BOM to 2024.09.00

Release 15.10.3

---

CHANGELOG.md
README.md
sample/app/build.gradle
sample/app/src/main/java/com/intercom/sample/MainActivity.kt
sample/app/src/main/java/com/intercom/sample/components/InputPanel.kt
sample/app/src/main/java/com/intercom/sample/components/SelfServePanel.kt
sample/app/src/main/java/com/intercom/sample/components/TextInputAlertDialog.kt
sample/app/src/main/java/com/intercom/sample/components/UserDetailsEditor.kt
sample/app/src/main/java/com/intercom/sample/components/UserUpdatePanel.kt
sample/app/src/main/java/com/intercom/sample/screens/HomeScreen.kt
sample/app/src/main/java/com/intercom/sample/ui/theme/Shape.kt
sample/app/src/main/java/com/intercom/sample/ui/theme/Theme.kt
sample/app/src/main/java/com/intercom/sample/ui/theme/Type.kt

- Fixed an issue causing conflicts when the host application integrates with Sentry
- Addressed a MalformedURLException that occurred during file downloads
- Fixed crash IllegalArgumentException: Cannot have an empty start destination route
- Fixed a bug where the device's language settings would override Messenger default language settings

Release 15.11.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Prevented ProGuard from removing critical classes during build time
* Resolved issues with downloading images in the app
* Bumped androidx.compose:compose-bom from 2024.10.00 to 2024.10.01. 
* Bumped androidx.compose.animation:animation-graphics-android from 1.6.8 to 1.7.5.

Release 15.11.2

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed the bug where users were unable to add a phone number in the attribute collector
* Fixed a crash caused by `IllegalArgumentException: y must be < bitmap.height()`
* Compose BOM: Updated to 2024.11.00
* AndroidX ConstraintLayout: Updated to 2.2.0
**Note**
This release contains some beta features.

Release 15.11.3

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Resolves an issue with Fin streaming replies.
* Compose BOM: Updated to 2024.12.01
* AndroidX Paging: Updated to 3.3.5
- This release contains some beta features.

Release 15.11.4

---

.gitignore
CHANGELOG.md
README.md
sample/app/build.gradle

* Revamped the “More” menu when launching directly into a conversation.
* Updates to the Powered By Intercom badge in conversations.
* Fixed a crash occurring when sending attachments.
* Fixed an issue where tapping push notifications wouldn’t open the conversation
* Firebase Messaging: Updated to 24.1.0

Release 15.11.5

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Added support for Fin for Platforms.
* Special notice view now supports links.
* This release contains some beta features.

Release 15.12.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Improved delineation between AI Agents and bots.
* New handover experience from AI Agents to teammates.
* Added Privacy Policy in the conversation screen
* Special notice now supports multiple languages.
* Intercom SDK now targets Android 15 (API level 35).
* Added edge-to-edge support
* Fixed the issue with new conversation workflow doesn’t trigger

Release 15.13.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* This release supports conditionally displaying attributes when filling out ticket forms.
* Improved scrolling performance on the conversation screen
* Added dynamic Fin thinking states
* Clicking a chat push notification now opens the Intercom conversation directly instead of first launching the launcher activity of your app.
* Fixed infinite loading in the conversation screen if a workflow contains an article

Release 15.14.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* We've added a new API to enable setting JWTs in the Messenger. This should be called before any user login. To learn more go [here](https://www.intercom.com/help/en/articles/10589769-authenticating-users-in-the-messenger-with-json-web-tokens-jwts).
* Resolved some differences between the registration of unidentified and identified users of iOS and Android. Both platforms now have matching implementations.

Release 15.16.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Added support for conversations merged across channels and users 
* Added support for setting a custom backstack item — You can now call `Intercom.pushBackStackActivity()` and set an activity you'd like as a backstack for Intercom push notifications
* Fixed an issue where Notes and Posts weren't showing in full
* Fixed IllegalArgumentException: Max number of dynamic shortcuts exceeded
* Fixed crashes on push notifications
* Compose BOM: Updated to 1.8.0 (via BOM 2025.04.00)
* Sentry: Updated to 8.11.1
* Gson: Updated to 2.13.0
* AndroidX ExifInterface: Updated to 1.4.1

Release 15.16.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Bug fixes and performance improvements
* Compose BOM: Updated to 1.8.1 (via BOM 2025.05.00)
* Gson: Updated to 2.13.1
* This version requires `compileSdk` version to be at least **35**. If you are not ready to use API level 35, please stay on the Intercom version 15.16.1

Release 16.0.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed a deadlock issue in `changeWorkspace` API that could occur when login API was called right after `changeWorkspace` API, causing the application to hang indefinitely while waiting for authentication.
* Sentry: Updated to 8.13.2

Release 16.2.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

We’re making conversations more natural and reducing the need for escalations.
- **More human, less rigid**: We’ve removed quick reply buttons so Fin can respond fluidly—no decision trees, just natural conversation.
- **Sources, now inline**: Fin now includes source links directly in replies, so customers can verify info at a glance.

Release 16.3.0

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed `NoSuchMethodError: No virtual method getParcelableArrayExtra` crash happening on lower Android versions
* Fixed `IllegalStateException: The specified child already has a parent` crash
* Fix in-app notification crash in Unity projects by improving legacy activity detection
* `com.google.firebase:firebase-messaging` to `24.1.2`

Release 17.0.1

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Fixed `ClassNotFoundException: androidx.compose.material.icons.Icons` crash

Release 17.0.2

---

CHANGELOG.md
README.md
sample/app/build.gradle

* Improved dark mode support
* Fixed issue where audio was missing in certain videos

Release 17.0.3
